### ISSUE TITLE
Server crash on player disconnect

### ISSUE THREAD

**Issue by MaegnusTheBlackMage** [Laike-Endaril/Fantastic-Lib#1]
Running:
SpongeForge: spongeforge-1.12.2-2825-7.1.6-RC3713
Forge: 14.23.5.2838
Fantasticlib: 1.12.2.012

It appears that certain players on disconnecting from the server are causing a server crash. below is the crash report.
[crash-2019-06-17_20.58.59-server.txt](https://github.com/Laike-Endaril/Fantastic-Lib/files/3299629/crash-2019-06-17_20.58.59-server.txt)

**Comment by Rhykes** [comment]
Also seeing this issue, without Spongeforge.

Players trying to connect with mod discrepancies between client/server cause our server to crash in our case, with a similar crash as reported above.

**Comment by Laike-Endaril** [comment]
Thanks for the report, I'll start looking into it

**Comment by Laike-Endaril** [comment]
Btw, if either of you have a full server log containing the crash (not just the crash report), that might be helpful in this case...maybe.  Idk for sure yet.

Alternatively, did you happen to notice this happening with a player that *just* logged in, and immediately logged out/got logged out?  Or even a player that never successfully logged in at all, but logged out regardless?  I believe I've actually seen that happen before.

Or is this known to happen under more normal circumstances (ie. a player has been logged in, and then logged out, and the server crashed)?

I'll start running tests to see if I can replicate it

**Comment by Laike-Endaril** [comment]
Alright, this should be fixed in 1.12.2.018.  Please tell me if you have any further issues ofc
