### ISSUE TITLE
crash with dynamic stealth?

### ISSUE THREAD

**Issue by Zack7292** [Laike-Endaril/Fantastic-Lib#2]
https://paste.dimdev.org/izateyivas.mccrash

don't know what happen, i just lunch my world and it crash

**Comment by Laike-Endaril** [comment]
This should now be fixed on the most recent version of DS (099) + fantasticlib (031)

Feel free to post here if you run into the same/similar issue ofc

**Comment by Zack7292** [comment]
Thx for fixing my issue!
