### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [Laike-Endaril/Fantastic-Lib#6]
1.12.2.045 has some sort of crash issue.

[crash-2021-06-04_13.19.56-client.txt](https://github.com/Laike-Endaril/Fantastic-Lib/files/6600825/crash-2021-06-04_13.19.56-client.txt)
Mods and other info in report.

**Comment by Laike-Endaril** [comment]
Fixed in 046, which will be available shortly

**Comment by MagmaSlime123** [comment]
Thank you.
