### ISSUE TITLE
Recent updates incompatible with Obfuscate lib

### ISSUE THREAD

**Issue by xJon** [Laike-Endaril/Fantastic-Lib#7]
Hi,
I know that you're not active anymore with mod development and that this might be fixable, but I figured I'd still report this for your information.
When updating from `44` to `46` I found that in combination with Obfuscate, a lot of player animations will break, e.g. swimming with [Idō Beta](https://www.curseforge.com/minecraft/mc-mods/ido/files/3096693) or sometimes when moving with armor equipped.

I am using Fantastic Lib because [Item Damage Rebalancer](https://github.com/Laike-Endaril/Item-Damage-Rebalancer) requires it, so I assume reverting to `44` will be okay?
Thanks!

**Comment by Laike-Endaril** [comment]
Yes, version 044 is fine for your purposes.

I may take a look into this however, as it sounds like the FLib animation systems are activating, which ideally they should not unless they're referenced (apparently I didn't program them that way the first time).

I don't plan to do any more feature releases, but crash and bug fixes could still be a thing (particularly for the jars I posted right at the end of my MC modding)

**Comment by xJon** [comment]
Thanks great, thanks!
If you build & upload the new version to CurseForge I'll be happy to test it.

**Comment by Laike-Endaril** [comment]
Fixed in 047
